### ISSUE TITLE
Parameter settings for training

### ISSUE THREAD

**Issue by UESTC-Med424-JYX** [hvcl/DiffMix#1]
Thank you very much for the excellent work, and could you please share the relevant parameter settings for training.
Multi-stage training is performed in the article Semantic Image Synthesis via Diffusion Models. Are the same settings used in your article?

**Comment by hjoh01** [comment]
Hello, thank you for having interest on this project!
I trained with the same settings as Semantic Image Synthesis via Diffusion Models (SDM) have used.
