### ISSUE TITLE
Share the checkpoint?

### ISSUE THREAD

**Issue by Liruieat** [hvcl/DiffMix#2]
Hi, I hope this message finds you well. 
First, I would like to thank you for sharing your impressive work on DiffMix. The research and implementation have been incredibly helpful for my own projects.
If it is possible, could you kindly share the checkpoints with me? Having access to these would greatly aid my progress and understanding.
I completely understand if there are any restrictions or if it is not possible to share them. Thank you very much for your time and assistance.

**Comment by hjoh01** [comment]
Hi,
I would upload and share the checkpoint in the near future.
After it is done, lemme leave a comment again.

**Comment by hjoh01** [comment]
I have added google drive links for the checkpoints. You check them and lemme know if there is another issue!

**Comment by Liruieat** [comment]
Hi, I hope this message finds you well. Thank you very much for providing the checkpoints; however, it seems that an application is required to obtain them. I have already submitted my application and hope to receive approval soon.

**Comment by hjoh01** [comment]
Hi, 
I updated the access authority for the checkpoints!
