### ISSUE TITLE
Enlarging Map

### ISSUE THREAD

**Issue by Liruieat** [hvcl/DiffMix#3]
Hello,

Thank you very much for your work. I noticed that the model framework diagram includes "enlarging map," but I could not find the specific implementation location in grad_mix. Additionally, most of the content appears to be similar to the work found at https://github.com/QuIIL/Grad_Mix. Have you made any additional designs to grad_mix.py? Could you please point out the location of the "Enlarging Map"?

**Comment by hjoh01** [comment]
Hello,

I've utilized the 'balancing map' code from the [Grad_Mix](https://github.com/QuIIL/Grad_Mix) repository, but I've developed additional code for the 'enlarging map'. The 'enlarging map' implementation involves randomly selecting nuclei indices from existing label maps and shifting them by 0-3 pixels in both x and y directions.
I'm currently locating the original code for the 'enlarging map' implementation in my working directory. Once found, I'll upload it to the repository.
