### ISSUE TITLE
GLySAC dataset

### ISSUE THREAD

**Issue by happywt** [hvcl/DiffMix#4]
Hello, thank you for your outstanding work. I am looking for the GLySAC dataset, but the link provided in Readme appears to be broken. Could you please provide an link to obtain GLySAC?

**Comment by bhosalems** [comment]
Yes, please.

**Comment by hjoh01** [comment]
Hello, 
I've uploaded the GLySAC dataset to Google Drive to provide an alternative access. 
You can now find the dataset at the following link: [GLySAC](https://drive.google.com/file/d/1g1_xYFWgp3cRLKrlSwD2U5JDjooC0yHp/view)

Please note that the original GLySAC dataset was provided by the [SONNET](https://github.com/QuIIL/Sonnet) project. You can find more information about GLySAC at their GitHub repository.
